# frozen_string_literal: true

require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/menu_sodas", type: :request do
  # MenuSoda. As you add validations to MenuSoda, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip("Add a hash of attributes valid for your model")
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  describe "GET /index" do
    it "renders a successful response" do
      MenuSoda.create! valid_attributes
      get menu_sodas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      menu_soda = MenuSoda.create! valid_attributes
      get menu_soda_url(menu_soda)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    xit "renders a successful response" do
      get new_menu_soda_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      menu_soda = MenuSoda.create! valid_attributes
      get edit_menu_soda_url(menu_soda)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MenuSoda" do
        expect do
          post menu_sodas_url, params: { menu_soda: valid_attributes }
        end.to change(MenuSoda, :count).by(1)
      end

      it "redirects to the created menu_soda" do
        post menu_sodas_url, params: { menu_soda: valid_attributes }
        expect(response).to redirect_to(menu_soda_url(MenuSoda.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MenuSoda" do
        expect do
          post menu_sodas_url, params: { menu_soda: invalid_attributes }
        end.to change(MenuSoda, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post menu_sodas_url, params: { menu_soda: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        skip("Add a hash of attributes valid for your model")
      end

      it "updates the requested menu_soda" do
        menu_soda = MenuSoda.create! valid_attributes
        patch menu_soda_url(menu_soda), params: { menu_soda: new_attributes }
        menu_soda.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the menu_soda" do
        menu_soda = MenuSoda.create! valid_attributes
        patch menu_soda_url(menu_soda), params: { menu_soda: new_attributes }
        menu_soda.reload
        expect(response).to redirect_to(menu_soda_url(menu_soda))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        menu_soda = MenuSoda.create! valid_attributes
        patch menu_soda_url(menu_soda), params: { menu_soda: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested menu_soda" do
      menu_soda = MenuSoda.create! valid_attributes
      expect do
        delete menu_soda_url(menu_soda)
      end.to change(MenuSoda, :count).by(-1)
    end

    it "redirects to the menu_sodas list" do
      menu_soda = MenuSoda.create! valid_attributes
      delete menu_soda_url(menu_soda)
      expect(response).to redirect_to(menu_sodas_url)
    end
  end
end
